
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project-Anime",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen p-0 grid grid-cols-1 grid-rows-[repeat(16,minmax(0,1fr))]`}
      >
        {/* <nav className="col-span-full md:flex row-end-1 md:row-end-2 items-center justify-center dark:text-white border-2 border-transparent md:p-0 m-0">
          <Navigation />
        </nav> */}

        <section className="rounded-2xl h-full row-[1/-1] md:row-span-full">
          {children}
        </section>
        <footer className="w-full bottom-0 text-center absolute text-sm">
            &copy;Data sourced from <a href="https://myanimelist.net/" target="_blank" rel="noopener noreferrer">MyAnimeList</a>
        </footer>
      </body>
    </html>
  );
}
