
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./ui/navigation";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project-Anime",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen p-0 grid grid-cols-1 grid-rows-12`}
      >
        <nav className="w-full flex items-center justify-center dark:text-white border-2 border-transparent p-2 md:p-0 m-0 row-end-2">
          <Navigation />
        </nav>

        <section className="w-full  h-full rounded-2xl row-[2/12] ">
          {children}
        </section>
        <footer className="w-full  h-full row-start-12 text-center text-xl">
            &copy;Data sourced from <a href="https://myanimelist.net/" target="_blank" rel="noopener noreferrer">MyAnimeList</a>
        </footer>
      </body>
    </html>
  );
}
